server.port: 80

# Spring Config
spring:
  application:
    name: vets-service
  boot:
    admin:
      client:
        auto-deregistration: true
        url: "http://admin-server.local.maesh"
        instance:
          prefer-ip: true
  cache:
    cache-names: vets
  cloud:
    refresh:
      refreshable: false
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://database-server:3306/petclinic?useSSL=false
    username: root
    password: petclinic
    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none

# Logging
logging.level.org.springframework: INFO
