agent:
  enabled: false
query:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
    - jaeger.spc.lab.nashdocker.io
    tls: []
cassandra:
  config:
    cluster_size: 1
    max_heap_size: 1024M
    heap_new_size: 256M
  resources:
    requests:
      memory: 2048Mi
      cpu: 0.4
    limits:
      memory: 2048Mi
      cpu: 0.4
  persistence:
    enabled: true
