server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Logging
logging.level.org.springframework: DEBUG

# Spring Config
spring:
  application:
    name: frontend-service
  messages:
    basename: messages/messages
  boot:
    admin:
      client:
        auto-deregistration: true
        url: "http://admin-server.local.maesh"
        instance:
          prefer-ip: true
