# Default values for spring-petclinic-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

env: {}

deployment:
  enabled: true

service:
  enabled: true
  type: ClusterIP
  port: 80

jaeger:
  enabled: false

canary:
  enabled: false
  serviceA: ""
  serviceB: ""

ingress:
  enabled: false
  rules: []

resources:
  requests:
    cpu: ".25"
    memory: "64Mi"
  limits:
    cpu: "1"
    memory: "128Mi"
nodeSelector: {}
tolerations: []
affinity: {}