server.port: 80

# Logging
logging.level.org.springframework: INFO

# Spring Config
spring:
  application:
    name: owners-service
  cloud:
    refresh:
      refreshable: false
  boot:
    admin:
      client:
        auto-deregistration: true
        url: "http://admin-server.local.maesh"
        instance:
          prefer-ip: true

customers-service:
  url: "http://customers-service.local.maesh"
  ribbon:
    eureka:
      enabled: false
visits-service:
  url: "http://visits-service.local.maesh"
  ribbon:
    eureka:
      enabled: false
