apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
    name: customers-service
    namespace: local
spec:
    service: customers-service
    backends:
    - service: customers-service-v1
      weight: 75
    - service: customers-service-v2
      weight: 25